### ISSUE TITLE
Having problems with LibHybris on Nexus 7 2013

### ISSUE THREAD

**Issue by depau** [libhybris/libhybris#245]
Hello,
I'm trying to run LibHybris on my Nexus 7 2013, running Arch Linux, in order to get hardware acceleration and maybe get wayland running. (https://github.com/crondog/arch-flo)

I followed the steps I've seen around the web in order to build it.
In particular I followed this guide: http://linux-rockchip.info/mw/index.php?title=LibHybris
and I used these PKGBUILD to install everything as a package: http://archlinuxarm.org/forum/viewtopic.php?f=33&t=5951

I built Android (I'm using the CyanogenMod source), patched bionic, rebuilt it, extracted /system and the headers, pushed them and installed them to the tablet, then built libhybris. (you can find my /system and headers here: http://download.tuxfamily.org/davidedduos/arch-flo/ ) 

LibHybris builds, but whenever I try to run almost any of the tests (gps and lights seem to work/not to crash) they either segfault or simply crash. This is their output: https://gist.github.com/Davideddu/779420a5a7393929df05

What can I do to troubleshoot this?

P.S.: I'm using CM nightly, which is 4.4.4 KitKat. The bionic patch applied without complaining, so I guessed it was ok. I'm asking because I saw the version of android you normally use is 4.2.2, which is not available on the Nexus 7 2013 as it started being sold after 4.3 was released.

**Comment by vrutkovs** [comment]
Started Sailfish port again, most of the bits required to build it are either upstream or PRs sent.

The only test worked for me is ```env EGL_PLATFORM=hwcomposer test_hwcomposer```, others fail shortly after checking for msaa. Note that I was using mer-hybris/libhybris@b981d65d17f6ffa8c3aa031d17eaf463d1c7d13b, will also try this on upstream libhybris

**Comment by vrutkovs** [comment]
More test results:
test_egl:
EGLPLATFORM=hwcomposer: crash:
```
#0  HWComposerNativeWindow::setup (this=0x0, gralloc=0xb6acb004, alloc=0x1a058) at hwcomposer_window.cpp:85
#1  0xb6ad0060 in hwcomposerws_CreateWindow (win=<optimized out>, display=<optimized out>) at eglplatform_hwcomposer.cpp:51
#2  0xb6f9d5b8 in ws_CreateWindow (win=0, display=0x0) at ws.c:67
#3  0xb6f9b5b8 in eglCreateWindowSurface (dpy=0x1, config=0x5, win=0, attrib_list=0xb6f99954) at egl.c:258
#4  0x00008998 in main ()
```

EGL_PLATFORM=null: pass
EGL_PLATFORM=fbdev: pass


test_glesv2:
EGL_PLATFORM=hwcomposer:
```
#0  HWComposerNativeWindow::setup (this=0x0, gralloc=0xb6acb004, alloc=0x1a058) at hwcomposer_window.cpp:85
#1  0xb6ad0060 in hwcomposerws_CreateWindow (win=<optimized out>, display=<optimized out>) at eglplatform_hwcomposer.cpp:51
#2  0xb6f9d5b8 in ws_CreateWindow (win=0, display=0x0) at ws.c:67
#3  0xb6f9b5b8 in eglCreateWindowSurface (dpy=0x1, config=0x5, win=0, attrib_list=0xb6f99954) at egl.c:258
#4  0x00008998 in main ()
```

EGL_PLATFORM=fbdev:
```
OpenGL ES 3.0 V@53.0 AU@  (CL@3776187)
frame:0
ERROR: fb->post(Invalid argument)
test_glesv2: fbdev_window.cpp:257: virtual int FbDevNativeWindow::queueBuffer(BaseNativeWindowBuffer*, int): Assertion `fbnb->busy==1' failed.
```

EGL_PLATFORM=null: pass

**Comment by kdub** [comment]
fwiw, mir (which uses the null libhybris platform) supports this device. you can look for inspiration there
