### ISSUE TITLE
Crash on 0x0000007fb7dda2d8 in XGetVisualInfo () from /lib/aarch64-linux-gnu/libX11.so.6

### ISSUE THREAD

**Issue by mifritscher** [libhybris/libhybris#439]
Using glmark2-es on a debian buster on a Planet Computer Cosmo (Mediatek P70 device, has kernel 4.4 and Android 9 as foundation), I get following:

```
Thread 1 "glmark2-es2" received signal SIGSEGV, Segmentation fault.
0x0000007fb7dda2d8 in XGetVisualInfo () from /lib/aarch64-linux-gnu/libX11.so.6
(gdb) bt
#0  0x0000007fb7dda2d8 in XGetVisualInfo () from /lib/aarch64-linux-gnu/libX11.so.6
#1  0x0000007fb76e7f18 in x11ws_eglGetConfigAttrib () from /usr/lib/aarch64-linux-gnu/libhybris//eglplatform_x11.so
#2  0x0000007fb78db7fc in eglGetConfigAttrib () from /usr/lib/aarch64-linux-gnu/libhybris-egl/libEGL.so.1
#3  0x0000005555564b64 in EglConfig::EglConfig (this=0x7fffffeb50, dpy=0x1, config=0x55556f9a58) at ../src/gl-state-egl.cpp:184
#4  0x000000555556599c in GLStateEGL::gotValidConfig (this=this@entry=0x7fffffef18) at ../src/gl-state-egl.cpp:648
#5  0x0000005555565acc in GLStateEGL::gotNativeConfig (this=0x7fffffef18, vid=@0x7fffffec58: 366505612496) at ../src/gl-state-egl.cpp:426
#6  0x0000005555561cf4 in CanvasGeneric::resize_no_viewport (this=this@entry=0x7fffffee78, width=800, height=600) at ../src/canvas-generic.cpp:225
#7  0x0000005555562b50 in CanvasGeneric::reset (this=0x7fffffee78) at ../src/canvas-generic.cpp:56
#8  0x000000555555ef38 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:205
(gdb) 
```

**Comment by mifritscher** [comment]
Ok, I just learned that on this device, the fork under https://github.com/gemian/libhybris is used.
